### ISSUE TITLE
slim wipes Data/clientpermissions.xml on "hard" restart

### ISSUE THREAD

**Issue by zuedev** [YanWenKun/barotrauma-server-docker#6]
### The Problem

To specify admins in the `slim` tag, we need to edit the `Data/clientpermissions.xml` file. Upon restarting the server by recreating the container, this file is reset to the default value of:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<ClientPermissions>  
</ClientPermissions>
```

### Reproducable Steps

**compose.yaml**
```yaml
version: "3"
services:
  barotrauma:
    image: yanwk/barotrauma-server:slim
    restart: unless-stopped
    ports:
      - "27015:27015/udp"
      - "27016:27016/udp"
    volumes:
      - "./data:/home/runner/Steam/steamapps/common/Barotrauma Dedicated Server"
```

1. Create **compose.yaml**
2. Run `docker compose up -d`
3. Wait for server to be ready
2. Run `docker compose down`
5. Edit **Data/clientpermissions.xml**
6. Run `docker compose up -d`
7. Notice that **Data/clientpermissions.xml** is reset to default value

### Temp Fix

Make the file read-only. I achieve this by adding this to my compose file:

```yaml
  volumes:
      - "./data/Data/clientpermissions.xml:/home/runner/Steam/steamapps/common/Barotrauma Dedicated Server/Data/clientpermissions.xml:ro"
```
